name: 'Check typescript'
on:
  push:
  paths:
      - packages/src/**
  pull_request:
   paths:
      - packages/src/**
jobs:
  typescript:
    name: typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn
      - name: tsc
        run: yarn tsc
